app1/urls.py
from django.urls import path
from . import views
app_name = 'app1'

# URL Cofiguration
urlpatterns = [
    path('hello/', views.say_hello),
    path('hi/', views.say_hi),
    path('posts/', views.blog_list),
    path('posts/<int:id>/', views.blog_detail, name='blog_detail'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/', include ('app1.urls'))
]

app1/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()

    def __str__(self):
        return self.title

app1/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Post

# Create your views here.
def say_hello(request):
    return HttpResponse('Hello Django')

def say_hi(request):
    return render(request, 'hi.html', {'name': 'Hershey De Luna Sambrano'})

def blog_list(request):
    post = Post.objects.all()
    context = {
        'blog_list': post
    }
    return render(request, 'blog_list.html', context)

def blog_detail(request, id):
    each_post = Post.objects.get(id = id)
    context = {
        'blog_detail': each_post
    }
    return render(request, 'blog_detail.html', context)

app1/templates/blog_detail.html
<h1> {{blog_detail.title}} </h1>
{{ blog_detail.content}}

app1/templates/blog_list.html
<h1> My blog list</h1>

<ul>
    {% for post in blog_list %}
    <li><a href="{% url 'app1:blog_detail' post.id %}">{{ post.title }}</a></li>
    {% endfor %}
</ul>

app1/templates/hi.html
{% if name %}
<h1> Hi {{name}} </h1>
{% else %}
<h1>Hi BulSUan</h1>
{% endif %}